### ISSUE TITLE
ActionView::Template::Error (Missing partial watchers_textinput/include_stylesheet with {:locale=>[:fr, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}.

### ISSUE THREAD

**Issue by a-herbe** [alvinchow86/redmine-watchers-textinput#1]
Configuration :
- Apache HTTPD + Phusion Passenger
- Redmine 2.3.2
- 'redmine' Context root added (via RailsBaseURI in Virtual Host Apache Configuration).

Without 'redmine-watchers-textinput', no problems...

When it's installed et activated, none pages are working.

Trace Log (With DEBUG LEVEL LOG) : 

Started GET "/redmine/" for 110.0.67.39 at 2013-08-13 15:34:54 +0200
Processing by WelcomeController#index as HTML
   (0.7ms)  SELECT MAX(`settings`.`updated_on`) AS max_id FROM `settings`
  User Load (0.8ms)  SELECT `users`.\* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 3 LIMIT 1
  Current user: a-herbe (id=3)
  SQL (0.9ms)  SELECT `news`.`id` AS t0_r0, `news`.`project_id` AS t0_r1, `news`.`title` AS t0_r2, `news`.`summary` AS t0_r3, `news`.`description` AS t0_r4, `news`.`author_id` AS t0_r5, `news`.`created_on` AS t0_r6, `news`.`comments_count` AS t0_r7, `projects`.`id` AS t1_r0, `projects`.`name` AS t1_r1, `projects`.`description` AS t1_r2, `projects`.`homepage` AS t1_r3, `projects`.`is_public` AS t1_r4, `projects`.`parent_id` AS t1_r5, `projects`.`created_on` AS t1_r6, `projects`.`updated_on` AS t1_r7, `projects`.`identifier` AS t1_r8, `projects`.`status` AS t1_r9, `projects`.`lft` AS t1_r10, `projects`.`rgt` AS t1_r11, `projects`.`inherit_members` AS t1_r12, `users`.`id` AS t2_r0, `users`.`login` AS t2_r1, `users`.`hashed_password` AS t2_r2, `users`.`firstname` AS t2_r3, `users`.`lastname` AS t2_r4, `users`.`mail` AS t2_r5, `users`.`admin` AS t2_r6, `users`.`status` AS t2_r7, `users`.`last_login_on` AS t2_r8, `users`.`language` AS t2_r9, `users`.`auth_source_id` AS t2_r10, `users`.`created_on` AS t2_r11, `users`.`updated_on` AS t2_r12, `users`.`type` AS t2_r13, `users`.`identity_url` AS t2_r14, `users`.`mail_notification` AS t2_r15, `users`.`salt` AS t2_r16 FROM `news` LEFT OUTER JOIN `projects` ON `projects`.`id` = `news`.`project_id` LEFT OUTER JOIN `users` ON `users`.`id` = `news`.`author_id` AND `users`.`type` IN ('User', 'AnonymousUser') WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='news')) ORDER BY news.created_on DESC LIMIT 5
  Project Load (1.1ms)  SELECT `projects`.\* FROM `projects` WHERE (projects.status <> 9) ORDER BY created_on DESC LIMIT 5
  UserPreference Load (0.8ms)  SELECT `user_preferences`.\* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 3 LIMIT 1
  Rendered news/_news.html.erb (2.5ms)
  Token Load (0.9ms)  SELECT `tokens`.\* FROM `tokens` WHERE `tokens`.`user_id` = 3 AND (action='feeds') LIMIT 1
  Rendered welcome/index.html.erb within layouts/base (7.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 500 Internal Server Error in 32ms

ActionView::Template::Error (Missing partial watchers_textinput/include_stylesheet with {:locale=>[:fr, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
- "/var/www/redmine/plugins/redmine_mylyn_connector/app/views"
- "/var/www/redmine/plugins/redmine_ldap_sync/app/views"
- "/var/www/redmine/plugins/redmine_inline_attach_screenshot/app/views"
- "/var/www/redmine/plugins/redmine_improved_searchbox/app/views"
- "/var/www/redmine/plugins/redmine_hudson/app/views"
- "/var/www/redmine/plugins/redmine_banner/app/views"
- "/var/www/redmine/plugins/redmine_advanced_issues/app/views"
- "/var/www/redmine/plugins/redirect_to_after_login/app/views"
- "/var/www/redmine/plugins/projects_tree_view/app/views"
- "/var/www/redmine/app/views"
  ):
  11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
  12: <%= javascript_heads %>
  13: <%= heads_for_theme %>
  14: <%= call_hook :view_layouts_base_html_head %>
  15: 
  16: <%= yield :header_tags -%>
  17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in`_app_views_layouts_base_html_erb__1028302097_89592740'
  app/controllers/application_controller.rb:397:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:395:in`render_error'
  app/controllers/application_controller.rb:383:in `render_404'
  app/controllers/application_controller.rb:407:in`missing_template'

**Comment by a-herbe** [comment]
Definitely, it's this line wich occurs problem :

**Comment by a-herbe** [comment]
Definitely, it's this line wich occurs problem :
[...]
require_dependency 'watchers_textinput/hooks'
[...]
in redmine-watchers-textinput-master/init.rb

Without this line Redmine start but, we can see that the plugin could not full load (It's logical).

Problem in path expression ? I'm not an expert.

**Comment by a-herbe** [comment]
Problem solved !

PLUGIN DIRECTORY MUST BE RENAMED INTO "watchers_textinput" in plugins directory.

**Comment by alvinchow86** [comment]
Sorry about that, and thanks for debugging! I've committed a fix.
